language: node_js
node_js: stable

install:
  - npm install hexo-cli -g
  - npm install
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "congcong93424"
  - git config user.email "congcong@liveu.xin"
  - git add .
  - git commit -m "add/edit"
  - git push -f -q "https://${github_token}@${GH_REF}" master:master
branches:
  only:
    - master

cache:
  directories:
    - node_modules

env:
  global:
    GH_REF: github.com/congcong93424/congcong93424.github.io.git